language: cpp

sudo: false

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - libgtest-dev
      - cmake
      - doxygen
      - python-virtualenv

before_install:
  - if [ $TRAVIS_BRANCH = "master" ]; then source docs/publish.sh; prepare; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - if [ $TRAVIS_BRANCH = "master" ]; then publish; fi
